### ISSUE TITLE
Add gitignore to uploads folder

### ISSUE THREAD

**Issue by juhitiwari** [AASF-IIITM/Emergency-Signal-Recognition-for-the-Hearing-Impaired-using-Multichannel-CNN#5]
In the folder flask deployment, there is a folder named uploads. This folder stores audio clips sent from android app and is used for making predictions. Add gitignore file and include this folder here so that it isn't uploaded in the remote repository.

**Comment by alpceylan** [comment]
I can take up this issue, can you assign me?

**Comment by juhitiwari** [comment]
> I can take up this issue, can you assign me?

Hey @alpceylan ! Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by Zeph-T** [comment]
@juhitiwari  mam, Can u assign me this task?

**Comment by juhitiwari** [comment]
> @juhitiwari mam, Can u assign me this task?

Sure, go ahead!
